### ISSUE TITLE
Add Integration Test with Embedded Database

### ISSUE THREAD

**Issue by Mom0aut** [Mom0aut/DynamicRelations#5]
Create Integration Tests with the https://github.com/zonkyio/embedded-database-spring-test Framework and choose an Embedded Postgres Database.

The Relation Service should be Integration tested.

**Comment by Vichukano** [comment]
Hallo! Can i take this issue?

**Comment by Mom0aut** [comment]
> 

hey sure 😄

**Comment by Mom0aut** [comment]
closed with #11
