### ISSUE TITLE
Add Flyway for the testing Database

### ISSUE THREAD

**Issue by Mom0aut** [Mom0aut/DynamicRelations#7]
Add the Flyway Core: https://mvnrepository.com/artifact/org.flywaydb/flyway-core/9.10.0
Add the Flyway Maven Plugin: https://flywaydb.org/documentation/usage/maven/
Add create SQL Files for the testing Entities under `src/main/resources/db/migration`

**Comment by Vichukano** [comment]
Hi! Can i take this?

**Comment by Mom0aut** [comment]
Sure go ahead 😄
